using System.Diagnostics; using System.Net; using System.Net.NetworkInformation; using System.Net.Sockets; using System.Windows; using System.Windows.Forms; using CloudPad.Protocol;
namespace CloudPad.Receiver;
public partial class MainWindow:Window
{
 readonly AppSettings settings; readonly ReceiverServer server; readonly NotifyIcon tray; bool exiting;
 public MainWindow(AppSettings settings){InitializeComponent();this.settings=settings;server=new(new Xbox360VirtualGamepad());server.Changed+=s=>Dispatcher.Invoke(()=>Render(s));server.InitializeGamepad();Render(server.Snapshot);
  PortBox.Text=settings.Port.ToString();TimeoutBox.Text=settings.PacketTimeoutMs.ToString();AutoStartCheck.IsChecked=settings.AutoStartServer;StartMinCheck.IsChecked=settings.StartMinimized;WindowsStartCheck.IsChecked=settings.StartWithWindows;LoggingCheck.IsChecked=settings.EnableLogging;PinText.Text=server.Pin;
  var (local,tail)=Addresses();LocalIpText.Text=$"Local IPv4: {local}";TailIpText.Text=$"Tailscale IPv4: {tail}";
  tray=new NotifyIcon{Text="CloudPad Receiver",Visible=true,Icon=System.Drawing.SystemIcons.Application};var menu=new ContextMenuStrip();menu.Items.Add("Open CloudPad",null,(_,_)=>ShowWindow());menu.Items.Add("Start Server",null,async(_,_)=>await Start());menu.Items.Add("Stop Server",null,(_,_)=>server.Stop());menu.Items.Add("Copy Tailscale IP",null,(_,_)=>{if(!tail.StartsWith("not"))System.Windows.Clipboard.SetText(tail);});menu.Items.Add("Show Pairing PIN",null,(_,_)=>{ShowWindow();});menu.Items.Add("Exit",null,(_,_)=>Exit());tray.ContextMenuStrip=menu;tray.DoubleClick+=(_,_)=>ShowWindow();Closing+=(s,e)=>{if(!exiting){e.Cancel=true;Hide();}};if(settings.AutoStartServer)_=Start();}
 static (string,string) Addresses(){var all=NetworkInterface.GetAllNetworkInterfaces().Where(n=>n.OperationalStatus==OperationalStatus.Up).SelectMany(n=>n.GetIPProperties().UnicastAddresses).Select(a=>a.Address).Where(a=>a.AddressFamily==AddressFamily.InterNetwork&&!IPAddress.IsLoopback(a)).ToList();var tail=all.FirstOrDefault(a=>{var b=a.GetAddressBytes();return b[0]==100&&(b[1]&0xC0)==64;});var local=all.FirstOrDefault(a=>!Equals(a,tail));return(local?.ToString()??"not detected",tail?.ToString()??"not detected");}
 async Task Start(){if(!int.TryParse(PortBox.Text,out var port)||port is <1 or >65535){System.Windows.MessageBox.Show("Enter a valid port (1–65535).","CloudPad");return;}if(!int.TryParse(TimeoutBox.Text,out var timeout)||timeout<100){System.Windows.MessageBox.Show("Packet timeout must be at least 100 ms.","CloudPad");return;}try{await server.StartAsync(port,timeout);if(!server.Snapshot.GamepadReady)System.Windows.MessageBox.Show("ViGEmBus bulunamadı veya kullanılamıyor. ViGEmBus kurulumunu ve Aygıt Yöneticisi'ndeki System devices bölümünü kontrol edin. Ayrıntılar log dosyasına yazıldı.","CloudPad Receiver",MessageBoxButton.OK,MessageBoxImage.Error);}catch(Exception ex){AppSettings.Log("Error",ex.ToString(),settings.EnableLogging);System.Windows.MessageBox.Show($"Sunucu başlatılamadı. 26760 portunun kullanımda olmadığını ve Windows Firewall iznini kontrol edin.\n\n{ex.Message}","CloudPad Receiver",MessageBoxButton.OK,MessageBoxImage.Error);}}
 void Render(ReceiverSnapshot s){StatusText.Text=$"Sunucu: {(s.Running?"Çalışıyor":"Durduruldu")} — {s.Message}";PhoneText.Text=s.PhoneConnected?$"Telefon bağlı: {s.Phone} ({s.PhoneIp})":"Telefon bağlantısı kesildi";PingText.Text=$"Ping: {s.Ping} ms";RateText.Text=$"Paket hızı: {s.PacketRate} paket/sn";ButtonsText.Text=$"Buttons: {(s.State.Buttons==0?"none":s.State.Buttons)}";SticksText.Text=$"Left X {s.State.LeftX:F2}  Y {s.State.LeftY:F2}\nRight X {s.State.RightX:F2}  Y {s.State.RightY:F2}";TriggersText.Text=$"LT {s.State.LeftTrigger:F2}    RT {s.State.RightTrigger:F2}";DriverText.Text=s.GamepadReady?"ViGEm bulundu — Xbox 360 Controller hazır":"ViGEm bulunamadı — sanal controller oluşturulamadı";}
 async void Start_Click(object s,RoutedEventArgs e)=>await Start();void Stop_Click(object s,RoutedEventArgs e)=>server.Stop();void NewPin_Click(object s,RoutedEventArgs e){server.GeneratePin();PinText.Text=server.Pin;}
 void Save_Click(object s,RoutedEventArgs e){if(int.TryParse(PortBox.Text,out var p))settings.Port=p;if(int.TryParse(TimeoutBox.Text,out var t))settings.PacketTimeoutMs=t;settings.AutoStartServer=AutoStartCheck.IsChecked==true;settings.StartMinimized=StartMinCheck.IsChecked==true;settings.StartWithWindows=WindowsStartCheck.IsChecked==true;settings.EnableLogging=LoggingCheck.IsChecked==true;settings.Save();System.Windows.MessageBox.Show("Settings saved. Restart the server after changing its port.");}
 void Setup_Click(object s,RoutedEventArgs e)=>Process.Start(new ProcessStartInfo("https://github.com/nefarius/ViGEmBus/releases"){UseShellExecute=true});void ShowWindow(){Show();WindowState=WindowState.Normal;Activate();}void Exit(){exiting=true;tray.Visible=false;tray.Dispose();server.Dispose();System.Windows.Application.Current.Shutdown();}
}
